name: neo4j
services:
  neo:
    image: neo4j:5.26.0-community-bullseye
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j:/data

volumes:
  neo4j:
    name: "hrynio-n4j"
